on:
  workflow_call:
    inputs:
      checkbox1:
        type: boolean
        required: true
        description: 'Production?'

jobs:
  test-in-workflow:
    runs-on: ubuntu-latest:
    steps:
      - run: |
          echo "Testing input: == true ${{ inputs.checkbox1 == true }}"
          echo "Testing input: == false ${{ inputs.checkbox1 == false }}"
          echo "Testing input: == 'true' ${{ inputs.checkbox1 == 'true' }}"
          echo "Testing input: == 'false' ${{ inputs.checkbox1 == 'false' }}"
